/* EDITABLE CONTENT: update verified business details and demo content here. */
const companyInfo={name:'MrFiga Corporate Consults',phone:'+234 802 539 1829',phoneLink:'+2348025391829',address:'9B Igbodo Street, Old GRA, Port Harcourt, Rivers State, Nigeria',whatsAppMessage:'Hello MrFiga Corporate Consults, I would like to make an enquiry about your business consulting services.'};
const services=[
 {icon:'bi-compass',title:'Business Strategy',desc:'[Demo service description — details to be confirmed.]',areas:'[Market position], [priorities], [growth planning]'},
 {icon:'bi-graph-up-arrow',title:'Business Development',desc:'[Demo service description — details to be confirmed.]',areas:'[Opportunities], [partnerships], [go-to-market]'},
 {icon:'bi-diagram-3',title:'Operations & Process Improvement',desc:'[Demo service description — details to be confirmed.]',areas:'[Workflows], [process review], [efficiency]'},
 {icon:'bi-briefcase',title:'Management Advisory',desc:'[Demo service description — details to be confirmed.]',areas:'[Leadership], [management systems], [decisions]'},
 {icon:'bi-file-earmark-text',title:'Business Planning',desc:'[Demo service description — details to be confirmed.]',areas:'[Plans], [objectives], [implementation]'},
 {icon:'bi-buildings',title:'Corporate Consulting',desc:'[Demo service description — details to be confirmed.]',areas:'[Corporate needs], [advisory], [solutions]'}];
const articles=['5 Ways Small Businesses Can Improve Operational Efficiency','How to Build a Practical Business Growth Strategy','Understanding Business Planning for SMEs','Common Management Challenges in Growing Businesses','How Better Processes Can Improve Business Performance','Building a Strong Foundation for Sustainable Growth'];
document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-year]').forEach(x=>x.textContent=new Date().getFullYear());document.querySelectorAll('[data-phone]').forEach(x=>x.textContent=companyInfo.phone);document.querySelectorAll('[data-address]').forEach(x=>x.textContent=companyInfo.address);const nav=document.querySelector('.navbar');const top=document.querySelector('.to-top');window.addEventListener('scroll',()=>{nav?.classList.toggle('scrolled',scrollY>30);top?.classList.toggle('show',scrollY>450)});top?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));document.querySelectorAll('.whatsapp').forEach(x=>x.href='https://wa.me/'+companyInfo.phoneLink.slice(1)+'?text='+encodeURIComponent(companyInfo.whatsAppMessage));renderServices();renderArticles();setupForm();const observer=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.15});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));});
function renderServices(){const box=document.querySelector('#service-list');if(!box)return;box.innerHTML=services.map((s,i)=>`<div class="col-md-6 col-lg-4"><article class="card-clean"><div class="service-icon"><i class="bi ${s.icon}"></i></div><h3 class="h4 mt-4">${s.title}</h3><p class="text-secondary">${s.desc}</p><button class="btn btn-link text-link p-0 service-btn" data-id="${i}" data-bs-toggle="modal" data-bs-target="#serviceModal">Learn more <i class="bi bi-arrow-right"></i></button></article></div>`).join('');box.querySelectorAll('.service-btn').forEach(b=>b.addEventListener('click',()=>{let s=services[b.dataset.id];document.querySelector('#serviceModalLabel').textContent=s.title;document.querySelector('#service-modal-body').innerHTML=`<p>${s.desc}</p><h3 class="h6">Key areas <span class="text-secondary fw-normal">(editable demo content)</span></h3><p>${s.areas}</p><h3 class="h6">Potential outcomes</h3><p>[Potential outcomes to be discussed and confirmed.]</p>`}));}
function renderArticles(){const box=document.querySelector('#article-list');if(!box)return;box.innerHTML=articles.map((a,i)=>`<div class="col-md-6 col-lg-4"><article class="card-clean"><span class="eyebrow">Demo article</span><p class="article-meta mt-3">[Date placeholder] · Business insight</p><h2 class="h4">${a}</h2><p class="text-secondary">[Sample preview copy for demonstration. Replace with approved editorial content.]</p><button class="btn btn-link text-link p-0 article-btn" data-title="${a}" data-bs-toggle="modal" data-bs-target="#articleModal">Read sample <i class="bi bi-arrow-right"></i></button></article></div>`).join('');box.querySelectorAll('.article-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelector('#articleModalLabel').textContent=b.dataset.title;document.querySelector('#article-modal-body').textContent='DEMO ARTICLE: [Sample article content to be written, reviewed and approved before publication.]'}));}
function setupForm(){const form=document.querySelector('#contactForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const msg=document.querySelector('#formMessage');const phone=form.phone.value.trim(),email=form.email.value.trim(),text=form.message.value.trim();if(!form.name.value.trim()||!email.match(/^[^\s@]+@[^\s@]+\.[^\s@]+$/)||phone.replace(/\D/g,'').length<7||text.length<10){msg.className='alert alert-danger mt-3';msg.textContent='Please complete all required fields with a valid email, phone number and message of at least 10 characters.';return}msg.className='alert alert-success mt-3';msg.textContent='Thank you. Your enquiry has been prepared successfully. A backend or email service can be connected here.';form.reset();});}
